---
# This playbook performs a rolling deploy to the staging cluster (cerium,
# praseodymium, xenon). After restarting each node, it waits for the node to
# become available.

# Execute with: ansible-playbook -i hosts restbase/deploy-staging.yml

- hosts: restbase-staging
  # Stop if more than 20% of boxes fail
  max_fail_percentage: 19
  # Run commands on node with sudo
  sudo: yes
  # one at a time
  serial: 1

  tasks:
  - name: check out the deploy repo
    git:
      repo: https://gerrit.wikimedia.org/r/mediawiki/services/restbase/deploy 
      dest: /srv/deployment/restbase/deploy
      version: origin/master
      force: true

  handlers:
  # Only executed if the git checkout changed
  - name: restart restbase
    service: name=restbase state=restarted

  post_tasks:
  - name: wait for restbase to come up
    wait_for: host={{ inventory_hostname }} port=7231 state=started timeout=180
