---
# This playbook replaces the trebuchet repos with straight checkouts from
# gerrit.

# Execute with: ansible-playbook -i hosts restbase/deploy-staging.yml

- hosts: restbase-staging
  max_fail_percentage: 20
  sudo: yes
  serial: 1

  tasks:
  - name: check if the deploy repo is pointing to tin
    shell: grep -c tin.eqiad /srv/deployment/restbase/deploy/.git/config || exit 0
    register: repo_check
    ignore_errors: true

  - name: remove the old deploy checkout
    file:  path=/srv/deployment/restbase/deploy state=absent
    when: repo_check.stdout != "0"
