---
# This playbook does a rolling restart of all restbase nodes, and checks their
# availability before proceeding.

# Execute with: ansible-playbook -i staging roles/restbase/restart.yml

- hosts: '{{target}}'
  max_fail_percentage: 10
  # No need for facts for basic deploys
  gather_facts: false
  sudo: yes
  serial: 1

  tasks:
    - include: tasks/restart.yml
