---
# This playbook replaces the trebuchet repos with straight checkouts from
# gerrit.

# Execute with: ansible-playbook -i hosts restbase/deploy-staging.yml

- hosts: '{{target}}'
  max_fail_percentage: 20
  sudo: yes
  serial: 1

  tasks:
  - name: check if the deploy repo is pointing to tin
    shell: grep -c tin.eqiad /srv/deployment/restbase/deploy/.git/config
    register: repo_check
    ignore_errors: true

  - name: remove the old deploy checkout
    file:  path=/srv/deployment/restbase/deploy state=absent
    #when: repo_check.stdout != "0"

  - include: tasks/deploy.yml

  - include: tasks/restart.yml
    when: deploy.changed
