- name: update the restbase config
  register: config
  template: 
    src: templates/{{restbase_config_template}}
    dest: /etc/restbase/config.yaml
    owner: root 
    group: restbase 
    mode: '0640'
