- name: depool restbase
  command: depool-restbase
  when: pool_restbase

- name: restart restbase
  service: name=restbase state=restarted

- include: check.yml

- name: repool back restbase
  command: pool-restbase
  when: pool_restbase
